#! /bin/bash

# Проверяем, установлен ли скрипт
if [! -f "/var/lib/webosbrew/init.d/homescreen_cleaner" ]; then
 # Загружаем скрипт, если он еще не установлен
 curl -s -L https://github.com/nnmdd/homescreen_cleaner/raw/main/homescreen_cleaner > /var/lib/webosbrew/init.d/homescreen_cleaner
 chmod +x /var/lib/webosbrew/init.d/homescreen_cleaner
 /var/lib/webosbrew/init.d/homescreen_cleaner && exit 0
fi

# Создаем временную директорию
mkdir -p /tmp/homescreen_cleaner

# Создаем QML-файлы, которые очищают домашний экран
echo "return" > /tmp/homescreen_cleaner/TopShelf.qml
echo "return" > /tmp/homescreen_cleaner/RecentBG.qml
echo "return" > /tmp/homescreen_cleaner/AppInterfaces.qml
echo "return" > /tmp/homescreen_cleaner/Recommended.qml
echo "return" > /tmp/homescreen_cleaner/CPShelf.qml
echo "return" > /tmp/homescreen_cleaner/AIBoard.qml
echo "return" > /tmp/homescreen_cleaner/AdShelf.qml
